#-----------------------------------------------------------------------------------
# On donne le nom "wordpress" à ce container,
# à partir de l'image "wordpress",
# on le lie à notre bdd nommée "db",
# sur le port 8081 de notre machine, qui pointe sur le port 80 de notre "container",
# puis pour finir on copie le "volume".
#-----------------------------------------------------------------------------------
# On donne le nom "wpmariadb" à ce container,
# à partir de la dernière image "mariadb",
# on init une variable "MYSQL_ROOT_PASSWORD = root",
# sur le port 3306 de notre machine, qui pointe sur le port 3306 de notre "container".
#-----------------------------------------------------------------------------------
# On donne le nom "wpphpmyadmin" à ce "container",
# à partir de l'image "phpmyadmin/phpmyadmin",
# on le lie à notre bdd nommée "db",
# on init 2 variables "MYSQL_USERNAME= root" et "MYSQL_ROOT_PASSWORD=root",
# sur le port 8080 de notre machine, qui pointe sur le port 80 de notre "container",
# on crée un volume "/sessions".
#-----------------------------------------------------------------------------------
# Ressources :
# https://docs.docker.com/compose/compose-file/#image
# https://docs.docker.com/compose/compose-file/#restart
# https://docs.docker.com/compose/compose-file/#volumes
# https://docs.docker.com/compose/compose-file/#environment
#-----------------------------------------------------------------------------------

# Version a utiliser pour le format du fichier docker-compose
version: "3"

services :

  # CONTAINER - MYSQL :
  # https://hub.docker.com/_/mysql
  db:
    image: sasicontainer.azurecr.io/common/mariadb:10.3
    container_name: wp_mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    logging:
      driver: awslogs
      options:
        awslogs-group: dockercomposetest
        awslogs-region: eu-central-1
        awslogs-stream-prefix: mariadb
    networks:
      - wp

  # CONTAINER - WORDPRESS :
  # https://hub.docker.com/_/wordpress
  wordpress:
    depends_on:
      - db
    image: sasicontainer.azurecr.io/common/wordpress:latest
    container_name: wp_wordpress
    restart: always
    #volumes: ["./:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: 127.0.0.1:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: dockercomposetest
        awslogs-region: eu-central-1
        awslogs-stream-prefix: wp_wordpress
    networks:
      - wp

  # CONTAINER - PHPMYADMIN :
  # https://hub.docker.com/r/phpmyadmin/phpmyadmin
  #phpmyadmin:
  #  depends_on:
  #    - db
  #  image: phpmyadmin/phpmyadmin
  #  container_name: wp_phpmyadmin
  #  restart: always
  #  environment:
  #    PMA_HOST: db
  #    MYSQL_ROOT_PASSWORD: password
  #  ports:
  #    - "80:80"
  #  logging:
  #    driver: awslogs
  #    options:
  #      awslogs-group: dockercomposetest
  #      awslogs-region: eu-central-1
  #      awslogs-stream-prefix: wp_php
    # networks:
    #   - wp

networks:
  wp:

volumes:
  db_data: